pipeline {
    agent { label 'jenkins-agent' }

    environment {
        IMAGE_NAME = 'springboot-app'
        IMAGE_TAG = 'v1'
        APP_DIR = 'spring-boot-app'
        DOCKERHUB_USER = 'miteshpatidar25'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Mitesh-Patidar/spring-boot-app-jenkins-pipline-agrocd-helm.git'
            }
        }

        stage('Build with Maven') {
            steps {
                dir("${APP_DIR}") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${APP_DIR}") {
                    sh 'docker build -t $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerid', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh """
                        echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
                        docker push $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG
                    """
                }
            }
        }

        
        stage('Deploy to Kubernetes using Helm') {
            steps {
                dir('helm-chart') {
                    sh """
                        helm upgrade --install $IMAGE_NAME . \
                        --set image.repository=$DOCKERHUB_USER/$IMAGE_NAME \
                        --set image.tag=$IMAGE_TAG \
                        --namespace default
                    """
                }
            }
        }
    }
}
